FROM almalinux
LABEL AUTHOR="BHARAT" \
      COURSE="DOCKER" \
      DURATION="25 HRS"
ENV   AUTHOR="PRIYA" \
      COURSE="K8S" \
      DURATION="25 HRS"
RUN yum install nginx -y
CMD ["nginx","-g","daemon off"]